import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Card from '@/components/Card';

export default function Home() {
  return (
    <>
      <Head>
        <title>PokeNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Card />
      </main>
    </>
  )
}
